# @package _global_
defaults:
  - common
  - common_plan
  # - models/worldmodel
  # - nn/worldmodel: WorldModelNet
  # - trainers/worldmodel

AgentClass:
  _target_: agents.PlanAgent

agent:
  plan:
    max_depth: 4
    n_options: 4
    probability: 0.8
    type: sparse
