# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    cpus_per_task: 2
    gpus_per_task: 0
    tasks_per_node: 1
    nodes: 1
    mem_gb: 2
    # additional_parameters:
    #   mail-user: jsyoo61@mit.edu
    #   mail-type: END
    array_parallelism: 2000
    timeout_min: 900 # 15 hours by default
